cache:
  - node_modules
install:
  - ps: Install-Product node 12
  - npm install -g codecov c8 nyc
  - npm ci
  - npm run build
  - c8 npm run test
  - c8 report --reporter=text-lcov > coverage.lcov
  - codecov
  - ps: Install-Product node 10
  - c8 npm run test
  - c8 report --reporter=text-lcov > coverage.lcov
  - codecov
  - ps: Install-Product node 8
  - nyc npm run test
  - codecov
build: off
